# Generated by Django 4.1.6 on 2023-04-28 06:59

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shape', models.CharField(choices=[('circle', 'circle'), ('square', 'square'), ('oval', 'oval'), ('rectange', 'rectangle')], default='circle', max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(default=True, upload_to='images')),
                ('weight', models.CharField(max_length=150)),
                ('price', models.PositiveBigIntegerField()),
                ('layers', models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three')], default='three', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_status', models.CharField(choices=[('in-carts', 'in-carts'), ('order-placed', 'order-placed'), ('cancelled', 'cancelled')], default='order-placed', max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cakes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_status', models.CharField(choices=[('shipped', 'shipped'), ('order-placed', 'order-place'), ('in-transit', 'in-transit'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('return', 'return')], default='shipped', max_length=100)),
                ('expected_deliverydate', models.DateField(default=datetime.date(2023, 4, 29))),
                ('address', models.CharField(max_length=260, null=True)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cakes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=240)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cakes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cakebox',
        ),
    ]
